/*
Checa uso de disco no ASM
*/

COL "NAME"     FORMAT A20
COL "TOTAL_GB" FORMAT A10
COL "USED_GB"  FORMAT A10
COL "FREE_GB"  FORMAT A10

SELECT
    NAME,
    TRUNC(TOTAL_MB/1024)||'G' AS TOTAL_GB,
    TRUNC((TOTAL_MB-FREE_MB)/1024)||'G' AS USED_GB,
    TRUNC(FREE_MB/1024)||'G' AS FREE_GB,
    TRUNC((TOTAL_MB-FREE_MB)/TOTAL_MB*100)||'%' AS "%_USED"
FROM V$ASM_DISKGROUP_STAT
ORDER BY NAME;

CLEAR COL