/*
Checa uso das tablespaces
*/

@set

ACCEPT VAR_TBS PROMPT 'INFORME O TABLESPACE: '
USR

/*
ALTER TABLESPACE QA_DATA ADD DATAFILE '/u04/app/oracle/oradata/orcl/qa_data07.dbf'
 size 2048m autoextend on next 512m maxsize 16384m;

CREATE TABLESPACE PERFDATA DATAFILE '+DATA/ORCL/perfdata01.dbf'
 size 512m autoextend on next 256m maxsize 16384m;
*/

COL "FILE NAME" FORMAT A200
COL "TABLE SPACE" FORMAT A25
COL "SIZE (MB)" FORMAT 999999999

SELECT TABLESPACE_NAME "TABLE SPACE",
	BYTES/1024/1024 "SIZE (MB)",
	STATUS "STATUS",
	AUTOEXTENSIBLE,
	'ALTER DATABASE DATAFILE '||CHR(39)||FILE_NAME||CHR(39)||' RESIZE ' || (BYTES/1024/1024) || 'm;'  "FILE NAME"
FROM
	DBA_DATA_FILES
WHERE UPPER(TABLESPACE_NAME) LIKE UPPER('%&VAR_TBS%')
ORDER BY TABLESPACE_NAME, FILE_ID;

CLEAR COL
UNDEF VAR_TBS
