/*
Traz informações de DB_LINK
*/
@set

COL "OWNER"    FORMAT A20
COL "USERNAME" FORMAT A20
COL "DB_LINK"  FORMAT A40
COL "HOST"     FORMAT A300

ACCEPT VAR_DBLINK PROMPT 'INFORME DB_LINK(PARTE) : '
ACCEPT VAR_OWNER PROMPT  'INFORME OWNER(PARTE)   : '

SELECT
    OWNER, DB_LINK, USERNAME, HOST,
    TO_CHAR(CREATED,'MM/DD/YYYY HH24:MI:SS') "CRIACAO"
FROM DBA_DB_LINKS
WHERE OWNER LIKE(UPPER('%&VAR_OWNER%'))
    AND DB_LINK LIKE(UPPER('%&VAR_DBLINK%'))
ORDER BY OWNER, DB_LINK;

CLEAR COL
UNDEF VAR_OWNER VAR_DBLINK

