SET LONG 20000 LONGCHUNKSIZE 20000 PAGESIZE 0 LINESIZE 1000 FEEDBACK OFF VERIFY OFF TRIMSPOOL ON
SET HEADING OFF

BEGIN
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'SQLTERMINATOR', true);
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform, 'PRETTY', true);
END;
/


ACCEPT VAR_SPOOL PROMPT 'INFORME O DIRETORIO DE SPOOL: '

spool "&VAR_SPOOL/EXP_PUBLIC_SYN_&_CONNECT_IDENTIFIER.SQL"

PROMPT SET ECHO ON
PROMPT SET FEEDBACK ON

SELECT DBMS_METADATA.get_ddl ('SYNONYM', synonym_name, owner)
FROM   dba_synonyms
WHERE  owner = 'PUBLIC'
AND TABLE_OWNER not in ('SYS', 'SYSTEM', 'ORDSYS', 'OWBSYS', 'XDB', 'ORDDATA', 'SYSMAN', 'DBSNMP', 'MDSYS', 'PERFSTAT', 'APEX_030200', 'OLAPSYS', 'WMSYS', 'CTXSYS', 'EXFSYS', 'APPQOSSYS');

SET HEADING ON
set FEEDBACK ON
SET VERIFY ON
SPOOL OFF

PROMPT "EXECUTE: @&VAR_SPOOL/EXP_PUBLIC_SYN_&_CONNECT_IDENTIFIER..SQL"