/*
Busca info. de view materializada e traz o comando para fazer o refresh manual
*/
SET VERIFY OFF

COL "OWNER"        FORMAT A20
COL "NOME DA VIEW" FORMAT A30
COL "ULTIMA ATT"   FORMAT A30

ACCEPT VAR_VNAME PROMPT 'NOME DA VIEW  : '
ACCEPT VAR_OWNER PROMPT 'NOME DO OWNER : '

SELECT OWNER "OWNER", MVIEW_NAME "NOME DA VIEW", LAST_REFRESH_DATE "ULTIMA ATT", 'exec DBMS_MVIEW.REFRESH(''' || OWNER || '.' || MVIEW_NAME || ''');' "ATUALIZAR"
	FROM DBA_MVIEWS
	WHERE OWNER LIKE ('%&VAR_OWNER%')
	AND MVIEW_NAME LIKE ('%&VAR_VNAME%');


CLEAR COL
UNDEF VAR_VNAME VAR_OWNER