/*
Lista info. de objetos da instancia
*/
SET VERIFY OFF

PROMPT
ACCEPT VAR_OBJ   PROMPT 'INFORME PARTE DO OBJETO : '
ACCEPT VAR_OWNER PROMPT 'INFORME PARTE DO OWNER  : '

COL "OBJECT_NAME" FORMAT A60
COL "OWNER"       FORMAT A20
COL "TYPE"        FORMAT A15

SELECT
	OWNER         "OWNER",
	OBJECT_NAME   "OBJECT_NAME",
	OBJECT_TYPE   "TYPE",
	STATUS        "STATUS",
	TO_CHAR(CREATED, 'DD/MM/YYYY') "CREATED",
	TO_CHAR(LAST_DDL_TIME, 'DD/MM/YYYY HH:MI') "LAST DDL TIME"
FROM
	DBA_OBJECTS
WHERE OBJECT_NAME LIKE upper('%&VAR_OBJ%')
    AND OWNER like Upper('%&VAR_OWNER%');

CLEAR COL
UNDEF VAR_OBJ VAR_OWNER