/*
Lista Scheduled Jobs
*/
COL "OWNER"           FORMAT A15
COL "JOB_NAME"        FORMAT A50
COL "START_DATE"      FORMAT A38
COL "END_DATE"        FORMAT A17
COL "REPEAT_INTERVAL" FORMAT A30
COL "STATE"           FORMAT A10
COL "ENABLED"         FORMAT A17
COL "JOB_ACTION"      FORMAT A50

SELECT OWNER, JOB_NAME, START_DATE, END_DATE, REPEAT_INTERVAL, STATE, ENABLED, JOB_ACTION FROM DBA_SCHEDULER_JOBS WHERE OWNER Like('%&1%');

CLEAR COL
UNDEF 1