SET LINES 900
SET PAGES 900
COL SCHEMA_NAME FOR A20
COL OCCUPANT_NAME FOR A25 
COL OCCUPANT_DESC FOR A55

SELECT SCHEMA_NAME,
    OCCUPANT_NAME,
    OCCUPANT_DESC,
    ROUND(SPACE_USAGE_KBYTES/1024) SPACE_USAGE_MB
FROM
    V$SYSAUX_OCCUPANTS
ORDER BY SPACE_USAGE_MB;
