/*
Traz informacoes de um usuario
*/

COL "NOME USUARIO"    FORMAT A20
COL "TBS DEFAULT"     FORMAT A20
COL "TBS TEMPORARIA"  FORMAT A14
COL "DATA CRIACAO"    FORMAT A21
COL "STATUS"          FORMAT A10
COL "DATA BLOQUEIO"   FORMAT A20
COL "TIPO OBJETO"     FORMAT A34
COL "PASSWORD"        FORMAT A20
COL "OWNER"           FORMAT A54
COL "TABLESPACE_NAME" FORMAT A31
COL "PROFILE"         FORMAT A15


SET VERIFY OFF

PROMPT
PROMPT == Users =============================================================================
SELECT 
	USERNAME             "NOME USUARIO",
	DEFAULT_TABLESPACE   "TBS DEFAULT",
	TEMPORARY_TABLESPACE "TBS TEMPORARIA",
	CREATED              "DATA CRIACAO",
	ACCOUNT_STATUS       "STATUS",
	LOCK_DATE            "DATA BLOQUEIO",
	PASSWORD             "PASSWORD",
	PROFILE              "PROFILE"		
FROM
	DBA_USERS
WHERE
	USERNAME LIKE UPPER('%&&1%')
ORDER BY
	USERNAME;

COL "NOME USUARIO"    FORMAT A40

PROMPT === Objetos ==========================================================================

SELECT
  OWNER "NOME USUARIO",
  COUNT(OBJECT_TYPE) "TOTAL",
  OBJECT_TYPE "TIPO OBJETO"
FROM
  DBA_OBJECTS
WHERE
  OWNER LIKE UPPER('%&1%')
GROUP BY OWNER, OBJECT_TYPE
ORDER BY OWNER, OBJECT_TYPE;

PROMPT == Tablespaces =======================================================================

SELECT DISTINCT
	OWNER,
	TABLESPACE_NAME
FROM
	DBA_SEGMENTS
WHERE
	OWNER LIKE UPPER('%&1%')
ORDER BY OWNER, TABLESPACE_NAME;
/*
COL "NOME USUARIO"   FORMAT A30
COL "PASSWORD" FORMAT A34
COL "LAST CHANGE" FORMAT A20

PROMPT == Password ==========================================================================

SELECT
	NAME "NOME USUARIO", PTIME "LAST CHANGE", PASSWORD
FROM
	SYS.USER$
WHERE
	NAME LIKE UPPER('%&1%');

COL "PASSWORD" FORMAT A55
*/
CLEAR COL
UNDEF 1

